// The Neuron mark, read from build/icon.json and rendered as SVG.
//
//   node tools/icons/icon-source.mjs        writes build/icon.svg
//
// Exported rather than only run, because tools/store-logos.mjs needs the same
// mark and used to carry its own copy of the polygons -- on a blue gradient, so
// the Store listing showed a different icon from the application.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

/** The mark's definition. The single place any of this is written down. */
export const icon = JSON.parse(readFileSync(join(root, 'build', 'icon.json'), 'utf-8'));

/**
 * The five branches, as `<polygon>` elements.
 *
 * Rotation is left to SVG's own transform rather than pre-computing the points:
 * appx-assets.py has to rotate them itself because Pillow has no equivalent, and
 * two implementations of the same trigonometry is how a half-pixel disagreement
 * becomes a debugging session.
 */
function branches() {
  const points = icon.branch.map(([x, y]) => `${x},${y}`).join(' ');
  const step = 360 / icon.branches;
  return Array.from({ length: icon.branches }, (_, i) =>
    `    <polygon points="${points}" transform="rotate(${Math.round(i * step)})"/>`,
  ).join('\n');
}

/**
 * How much of its own box the drawn mark actually spans.
 *
 * The branches reach 136 units out of 512, so the visible asterisk is only
 * ~53% of the box it is declared in. Sizing a tile by the box leaves it looking
 * mostly empty, which is why every caller wants coverage instead. Derived from
 * the branch points rather than written down again -- the 136 was previously
 * hardcoded a second time in appx-assets.py.
 */
export const markExtent =
  (2 * Math.max(...icon.branch.map(([, y]) => Math.abs(y)))) / icon.viewBox;

/**
 * The box to declare so the VISIBLE mark spans `coverage` of `size`.
 *
 * The appx tiles use 0.60; anything sharing a Start menu or a Store listing
 * with them should use the same, or the same icon looks like two icons.
 */
export const markBoxFor = (size, coverage) => Math.round((size * coverage) / markExtent);

/** The complete app icon: the mark on its rounded plate, edge to edge. */
export function iconSvg() {
  const { viewBox: v, cornerRadius, plate, mark } = icon;
  return `<!-- Generated by tools/icons/icon-source.mjs from build/icon.json. Do not edit. -->
<svg width="${v}" height="${v}" viewBox="0 0 ${v} ${v}" xmlns="http://www.w3.org/2000/svg">
  <rect x="0" y="0" width="${v}" height="${v}" rx="${cornerRadius}" fill="${plate}"/>
  <g transform="translate(${v / 2},${v / 2})" fill="${mark}">
${branches()}
  </g>
</svg>
`;
}

/**
 * Just the mark, no plate, at a given pixel size.
 *
 * For surfaces that draw their own background -- the Store logo pages put the
 * mark on a full-bleed plate rather than a 512-unit rounded square.
 */
export function markSvg(size) {
  const { viewBox: v, mark } = icon;
  return `<svg width="${size}" height="${size}" viewBox="0 0 ${v} ${v}" aria-hidden="true">
    <g transform="translate(${v / 2},${v / 2})" fill="${mark}">
${branches()}
    </g>
  </svg>`;
}

const isMain = import.meta.url.endsWith(String(process.argv[1]).replace(/\\/g, '/'));
if (isMain) {
  const out = join(root, 'build', 'icon.svg');
  writeFileSync(out, iconSvg(), 'utf-8');
  console.log(`wrote ${out}`);
}
